server:
  port: 8081


spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/userdb_holydev?useSSL=false&serverTimezone=Asia/Ho_Chi_Minh&allowPublicKeyRetrieval=true
    username: root
    password: Ch@/12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms


      lettuce:
        pool:
          max-active: 8        # tối đa 8 connection đồng thời
          max-idle: 8
          min-idle: 2
          max-wait: 1000ms     # chờ tối đa 1s nếu pool đầy
  cache:
    type: redis
    redis:
      time-to-live: 600000
      cache-null-values: false  # không cache giá trị null
      use-key-prefix: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

