spring:
  application:
    name: order-service

  datasource:
    url: jdbc:mysql://localhost:3306/orderdb_holydev?useSSL=false&serverTimezone=Asia/Ho_Chi_Minh&allowPublicKeyRetrieval=true
    username: root
    password: Ch@/12345678
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


feign:
  client:
    config:
      default:
        connect-timeout: 3000
        read-timeout: 10000
        logger-level: BASIC
      product-service:
        connect-timeout: 2000
        read-timeout: 5000
  circuitbreaker:
    enabled: true


server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka